version: "3.9"

services:
  web:
    image: juanchogonza98/proyecto_is2:latest
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/uploads
      - modules_volume:/app/modulos
      - gunicorn_socket:/app/gunicorn
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/proyecto_is2.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/proxy_params:/etc/nginx/proxy_params
      - static_volume:/app/static
      - modules_volume:/app/modulos
      - media_volume:/app/uploads
      - gunicorn_socket:/app
    depends_on:
      - web

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: proyecto
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  modules_volume:
  static_volume:
  media_volume:
  db_data:
  gunicorn_socket:
